name: Build Caddy

on:
  push:
    branches: 
        - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate date string
        id: date
        run: echo "date=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Checkout Dockerfile
        uses: actions/checkout@v3

      - name: Get latest caddy tag
        id: caddy
        run: |
          tag=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/library/caddy/tags?page_size=1024'| jq '."results"[]["name"]' -r | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' --color=never | head -n 1)
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Append Dockerfile
        run: |
          echo >> Dockerfile
          echo "LABEL org.opencontainers.image.created=$(env TZ="UTC" date --rfc-3339=seconds | sed 's/ /T/')" >> Dockerfile
          echo "LABEL org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}" >> Dockerfile
          echo "LABEL org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}" >> Dockerfile
          echo "LABEL org.opencontainers.image.version=${{ steps.caddy.outputs.tag }}" >> Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            CADDY_VERSION=${{ steps.caddy.outputs.tag }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/mplus-oss/caddy:latest
            ghcr.io/mplus-oss/caddy:${{ steps.caddy.outputs.tag }}
